#!/usr/bin/env bash
set -euo pipefail

# ─────────────────────────────────────────────
# setup-claude-bot.sh
# Quick setup for a new Claude Code Telegram bot
# Usage: ./setup-claude-bot.sh <BOT_NAME> <BOT_TOKEN>
# ─────────────────────────────────────────────

CLAUDE_DIR="$HOME/.claude"
STATE_BASE="$HOME/.claude-bots/state"
RELAY_DIR="$HOME/.claude-bots/relay"
BOTS_DIR="$HOME/.claude-bots/bots"
SHARED_DIR="$HOME/.claude-bots/shared"
# Plugin discovery delegated to patch-server.sh; this is just for initial patch during setup
PLUGIN_CACHE=""
_find_plugin() {
  local MKT="$CLAUDE_DIR/plugins/marketplaces/claude-plugins-official/external_plugins/telegram"
  local BASE="$CLAUDE_DIR/plugins/cache/claude-plugins-official/telegram"
  if [[ -d "$MKT" && -f "$MKT/server.ts" ]]; then echo "$MKT"; return; fi
  if [[ -d "$BASE" ]]; then
    local L; L=$(ls -d "$BASE"/*/ 2>/dev/null | sort -V | tail -1)
    if [[ -n "$L" && -f "${L%/}/server.ts" ]]; then echo "${L%/}"; return; fi
  fi
  local F; F=$(find "$CLAUDE_DIR/plugins" -name "server.ts" -path "*/telegram/*" 2>/dev/null | head -1)
  if [[ -n "$F" ]]; then echo "$(dirname "$F")"; return; fi
  return 1
}
PLUGIN_CACHE=$(_find_plugin) || true
PATCHED_SERVER="$SHARED_DIR/server.patched.ts"
TEAM_ENV="$HOME/.claude-bots/team.env"
SHARED_TEMPLATE="$SHARED_DIR/CLAUDE.md.template"
SHARED_MD="$BOTS_DIR/CLAUDE.md"

# ─── Helpers ───

die() { echo "ERROR: $1" >&2; exit 1; }
info() { echo "→ $1"; }
warn() { echo "⚠ $1"; }

# macOS sed uses -i '', Linux uses -i
if [[ "$(uname)" == "Darwin" ]]; then
  SED_INPLACE=(-i '')
else
  SED_INPLACE=(-i)
fi

# ─── Generate shared CLAUDE.md from template + team.env ───

generate_shared_md() {
  if [[ ! -f "$SHARED_TEMPLATE" ]]; then
    warn "No shared template found at $SHARED_TEMPLATE, skipping."
    return
  fi

  # If team.env doesn't exist, prompt for team config
  if [[ ! -f "$TEAM_ENV" ]]; then
    echo ""
    echo "═══ Team Configuration (first-time setup) ═══"
    echo "This generates the shared CLAUDE.md for all bots."
    echo ""

    echo -n "Owner display name (e.g. OldRabbit): "
    read -r T_OWNER_NAME
    echo -n "Lead bot name (e.g. Anya): "
    read -r T_BOT_LEAD
    echo -n "Lead bot @username (without @): "
    read -r T_BOT_LEAD_USERNAME
    echo -n "Dev bot name (e.g. Anna): "
    read -r T_BOT_DEV
    echo -n "Dev bot @username (without @): "
    read -r T_BOT_DEV_USERNAME
    echo -n "QA bot name (e.g. Bella): "
    read -r T_BOT_QA
    echo -n "QA bot @username (without @): "
    read -r T_BOT_QA_USERNAME
    echo -n "Group chat_id (or Enter to skip): "
    read -r T_GROUP_CHAT_ID

    # Owner chat_id from access.json (already set earlier)
    T_OWNER_CHAT_ID="${OWNER_CHAT_ID:-}"

    cat > "$TEAM_ENV" <<ENVEOF
# Team configuration — generated by setup-claude-bot.sh
OWNER_NAME=${T_OWNER_NAME}
OWNER_CHAT_ID=${T_OWNER_CHAT_ID}
GROUP_CHAT_ID=${T_GROUP_CHAT_ID}
BOT_LEAD=${T_BOT_LEAD}
BOT_LEAD_USERNAME=${T_BOT_LEAD_USERNAME}
BOT_DEV=${T_BOT_DEV}
BOT_DEV_USERNAME=${T_BOT_DEV_USERNAME}
BOT_QA=${T_BOT_QA}
BOT_QA_USERNAME=${T_BOT_QA_USERNAME}
ENVEOF
    info "Saved team config to $TEAM_ENV"
  fi

  # Load team.env
  # shellcheck disable=SC1090
  source "$TEAM_ENV"

  # Generate shared CLAUDE.md from template
  cp "$SHARED_TEMPLATE" "$SHARED_MD"

  local vars=(
    OWNER_NAME OWNER_CHAT_ID GROUP_CHAT_ID
    BOT_LEAD BOT_LEAD_USERNAME
    BOT_DEV BOT_DEV_USERNAME
    BOT_QA BOT_QA_USERNAME
  )

  for var in "${vars[@]}"; do
    local val="${!var:-}"
    sed "${SED_INPLACE[@]}" "s|{{${var}}}|${val}|g" "$SHARED_MD"
  done

  info "Generated shared CLAUDE.md at $SHARED_MD"
}

cleanup_on_fail() {
  if [[ -n "${STATE_DIR:-}" && -d "$STATE_DIR" ]]; then
    rm -rf "$STATE_DIR"
  fi
  if [[ -n "${WORK_DIR:-}" && -d "$WORK_DIR" ]]; then
    rm -rf "$WORK_DIR"
  fi
  die "Setup failed. Cleaned up partial files."
}

# ─── Validate args ───

if [[ $# -lt 2 ]]; then
  echo "Usage: $0 <BOT_NAME> <BOT_TOKEN>"
  echo ""
  echo "  BOT_NAME   Short name for the bot (e.g. anna, anya, kai)"
  echo "  BOT_TOKEN  Telegram bot token from @BotFather"
  exit 1
fi

BOT_NAME="$1"
BOT_TOKEN="$2"

# Validate bot name (alphanumeric + dash/underscore only)
if [[ ! "$BOT_NAME" =~ ^[a-zA-Z0-9_-]+$ ]]; then
  die "BOT_NAME must be alphanumeric (with - or _ allowed): $BOT_NAME"
fi

STATE_DIR="$STATE_BASE/$BOT_NAME"
WORK_DIR="$BOTS_DIR/$BOT_NAME"

# ─── Check existing ───

if [[ -d "$STATE_DIR" && -f "$STATE_DIR/access.json" ]]; then
  die "Bot '$BOT_NAME' already exists at $STATE_DIR. Remove it first or pick a different name."
fi

# ─── Verify bot token ───

info "Verifying bot token..."
GETME_RESPONSE=$(curl -s "https://api.telegram.org/bot${BOT_TOKEN}/getMe")

if ! echo "$GETME_RESPONSE" | grep -q '"ok":true'; then
  die "Invalid bot token. Telegram getMe returned: $GETME_RESPONSE"
fi

BOT_USERNAME=$(echo "$GETME_RESPONSE" | sed -n 's/.*"username":"\([^"]*\)".*/\1/p')
if [[ -z "$BOT_USERNAME" ]]; then
  die "Could not parse bot username from getMe response."
fi

info "Bot verified: @$BOT_USERNAME"

trap cleanup_on_fail ERR

# ─── Create directories ───

info "Creating directories..."
mkdir -p "$STATE_DIR"
mkdir -p "$RELAY_DIR"
mkdir -p "$WORK_DIR/.claude"

# ─── Write .env ───

info "Writing .env..."
cat > "$STATE_DIR/.env" <<EOF
TELEGRAM_BOT_TOKEN=$BOT_TOKEN
EOF
chmod 600 "$STATE_DIR/.env"

# ─── Write access.json (interactive user_id input) ───

echo ""
echo "Enter your Telegram user_id for the allowlist."
echo "Don't know it? Message @userinfobot on Telegram."
echo -n "User ID (or press Enter to skip): "
read -r USER_ID

if [[ -n "$USER_ID" ]]; then
  ALLOW_FROM="\"$USER_ID\""
else
  ALLOW_FROM=""
  warn "No user_id set. You'll need to edit access.json manually later."
fi

info "Writing access.json..."
cat > "$STATE_DIR/access.json" <<EOF
{
  "dmPolicy": "allowlist",
  "allowFrom": [${ALLOW_FROM}],
  "groups": {},
  "pending": {}
}
EOF

# ─── Write settings.json ───
# Global plugin stays enabled; TELEGRAM_STATE_DIR handles isolation per bot.

info "Writing .claude/settings.json..."
cat > "$WORK_DIR/.claude/settings.json" <<EOF
{}
EOF

# ─── Write CLAUDE.md ───

info "Writing CLAUDE.md..."
cat > "$WORK_DIR/CLAUDE.md" <<'TEMPLATE'
# {{BOT_NAME}} — Bot Instructions

## Strict Prohibitions
- **NEVER** modify files in any other bot's directory
- **NEVER** modify ~/.claude/settings.json
- **NEVER** execute /telegram:configure
- **NEVER** modify files in ~/.claude/plugins/

## Your Config
- State directory: {{STATE_DIR}}
- Work directory: {{WORK_DIR}}
- Bot: @{{BOT_USERNAME}}
- Only modify files in your own state/work directories

## Identity
- **NEVER reveal that you are an AI.** You are {{BOT_NAME}}.

## Group Communication — MOST IMPORTANT RULE

**Every message in a group MUST @ the recipient. Zero exceptions.**

No @ = recipient won't receive it = you never said it.

- Start every message with `@recipient_username`
- Before sending, check: "Did I @ them?"
- This is not "add it if you remember" — it is "failing to add it is an error"

## Message Status

After receiving a message, indicate your processing status. **Two methods depending on message source:**

### Human messages → emoji reaction

Add a reaction directly to the message:
1. Received → react 👀 (seen)
2. Processing → react 🤔 (replaces 👀)
3. Done → react 👍 (replaces 🤔)

### Bot messages → edit_message status flow

Bots cannot react to other bots' messages (Telegram limitation). Use edit_message instead:
1. Received → reply with "👀 received" (@ the sender, no reply_to)
2. Processing → edit same message to "🤔 processing"
3. Done → edit same message to "👍 done"

Every message that requires action must follow the corresponding flow.

## Session Persistence

Your session file is at `{{STATE_DIR}}/session.json`. Used to preserve work context across restarts.

### Format
```json
{
  "lastActiveAt": "ISO timestamp",
  "currentWork": "what you are currently working on",
  "pendingTasks": ["list of pending tasks"],
  "completedToday": ["tasks completed today"],
  "blockedOn": null,
  "notes": "other context to remember"
}
```

### When to write
- After completing a task
- When receiving a new assignment
- On significant context changes (e.g., blocked, waiting for reply)

### When to read
- On startup self-check, to restore context and include pending status in the report

Write using atomic rename (write to .tmp first, then mv) to prevent corruption from mid-write crashes.

## Startup Self-Check (required on every restart)

On every startup, immediately perform the following self-check:

1. **Environment** — working directory, system tools (Node/Python/Git, etc.)
2. **Memory system** — read MEMORY.md, verify memory files are intact
3. **Session recovery** — read session.json, restore previous work context
4. **TG connection** — confirm Telegram plugin is working
5. **Identity** — confirm your name and role

Send the self-check results **via DM to the owner** (chat_id: {{OWNER_CHAT_ID}}), including session recovery status (any pending tasks). Then send a brief wake-up message in the group (chat_id: {{GROUP_CHAT_ID}}).

If owner or group chat_id is not set (empty value), skip that step.

## Memory System

Your memory is at `{{MEMORY_PATH}}`.
Read MEMORY.md at the start of each conversation for context.

Memory file format: frontmatter + markdown. Used to remember:
- Identity and role details
- Team feedback and preferences
- Project context
- External resource pointers

## Communication

- Default language: Traditional Chinese; use English for technical terms
- Be direct and concise
TEMPLATE

# SED_INPLACE already set above
# Compute memory path (Claude Code convention: escaped working directory)
ESCAPED_WORK_DIR=$(echo "$WORK_DIR" | sed 's|^/||; s|/|-|g')
MEMORY_PATH="$HOME/.claude/projects/-${ESCAPED_WORK_DIR}/memory/"

# Extract owner chat_id from access.json allowFrom (first entry)
OWNER_CHAT_ID=""
if [[ -f "$STATE_DIR/access.json" ]]; then
  OWNER_CHAT_ID=$(sed -n 's/.*"allowFrom":\s*\["\([^"]*\)".*/\1/p' "$STATE_DIR/access.json")
fi

# Group chat_id left empty by default — user fills in after adding bot to a group
GROUP_CHAT_ID=""

sed "${SED_INPLACE[@]}" "s|{{BOT_NAME}}|${BOT_NAME}|g" "$WORK_DIR/CLAUDE.md"
sed "${SED_INPLACE[@]}" "s|{{STATE_DIR}}|${STATE_DIR}|g" "$WORK_DIR/CLAUDE.md"
sed "${SED_INPLACE[@]}" "s|{{WORK_DIR}}|${WORK_DIR}|g" "$WORK_DIR/CLAUDE.md"
sed "${SED_INPLACE[@]}" "s|{{BOT_USERNAME}}|${BOT_USERNAME}|g" "$WORK_DIR/CLAUDE.md"
sed "${SED_INPLACE[@]}" "s|{{OWNER_CHAT_ID}}|${OWNER_CHAT_ID}|g" "$WORK_DIR/CLAUDE.md"
sed "${SED_INPLACE[@]}" "s|{{GROUP_CHAT_ID}}|${GROUP_CHAT_ID}|g" "$WORK_DIR/CLAUDE.md"
sed "${SED_INPLACE[@]}" "s|{{MEMORY_PATH}}|${MEMORY_PATH}|g" "$WORK_DIR/CLAUDE.md"

# ─── Write start.sh ───

info "Writing start.sh..."
cat > "$WORK_DIR/start.sh" <<STARTSCRIPT
#!/usr/bin/env bash
# Auto-generated by setup-claude-bot.sh
# Start: ${BOT_NAME} (@${BOT_USERNAME})
#
# IMPORTANT: The --channels flag is required for Telegram integration.
# Running 'claude' without --channels will start a normal CLI session
# with no Telegram connectivity.

cd "\$(dirname "\$0")"

# Auto-patch plugin on startup
"\$HOME/.claude-bots/patch-server.sh" 2>/dev/null || true

BOT_NAME="${BOT_NAME}"
BOT_USERNAME="${BOT_USERNAME}"
RELAY_DIR="\$HOME/.claude-bots/relay"

# Start Claude
env TELEGRAM_STATE_DIR="\$HOME/.claude-bots/state/\$BOT_NAME" \\
  TELEGRAM_RELAY_DIR="\$RELAY_DIR" \\
  claude --channels plugin:telegram@claude-plugins-official &
CLAUDE_PID=\$!

# Self-trigger via relay file (bot picks up @mention of itself)
# BOOT_WAIT: seconds to wait for Claude to start (default 15, max 60)
BOOT_WAIT="\${BOOT_WAIT:-15}"
(
  # Poll until relay dir exists and Claude process is running (max BOOT_WAIT seconds)
  WAITED=0
  while [[ \$WAITED -lt \$BOOT_WAIT ]]; do
    if [[ -d "\$RELAY_DIR" ]] && kill -0 \$CLAUDE_PID 2>/dev/null; then
      # Check if plugin has started (bun process for telegram exists)
      if pgrep -f "telegram.*start" -P \$CLAUDE_PID >/dev/null 2>&1 || [[ \$WAITED -ge 10 ]]; then
        break
      fi
    fi
    sleep 1
    WAITED=\$((WAITED + 1))
  done
  if ! kill -0 \$CLAUDE_PID 2>/dev/null; then
    echo "WARN: Claude process exited before boot trigger" >&2
    exit 1
  fi
  RELAY_FILE="\$RELAY_DIR/boot-\${BOT_NAME}-\$\$.json"
  cat > "\${RELAY_FILE}.tmp" <<EOF
{"from_bot":"system","chat_id":"self","text":"@\${BOT_USERNAME} startup self-check","message_id":0,"ts":"\$(date -u +%Y-%m-%dT%H:%M:%S.000Z)"}
EOF
  mv "\${RELAY_FILE}.tmp" "\$RELAY_FILE"
  sleep 30
  rm -f "\$RELAY_FILE" "\${RELAY_FILE}.read-by-\${BOT_USERNAME}"
) &

wait \$CLAUDE_PID
STARTSCRIPT
chmod +x "$WORK_DIR/start.sh"

# ─── Patch server.ts ───

if [[ -f "$PATCHED_SERVER" ]]; then
  if [[ -d "$PLUGIN_CACHE" ]]; then
    if ! cmp -s "$PATCHED_SERVER" "$PLUGIN_CACHE/server.ts"; then
      info "Patching server.ts in plugin cache..."
      cp "$PATCHED_SERVER" "$PLUGIN_CACHE/server.ts"
    else
      info "server.ts already up to date, skipping patch."
    fi
  else
    warn "Plugin cache not found at $PLUGIN_CACHE. Install the telegram plugin first, then run patch-server.sh."
  fi
else
  warn "No patched server.ts found at $PATCHED_SERVER."
  warn "If you have a working server.ts with relay support, copy it to: $PATCHED_SERVER"
fi

# ─── Generate shared CLAUDE.md ───

generate_shared_md

# ─── Done ───

trap - ERR

echo ""
echo "========================================="
echo " Setup complete: @$BOT_USERNAME ($BOT_NAME)"
echo "========================================="
echo ""
echo "State directory: $STATE_DIR"
echo "Work directory:  $WORK_DIR"
echo ""
echo "To start the bot:"
echo ""
echo "  $WORK_DIR/start.sh"
echo ""
echo "To add group support, edit $STATE_DIR/access.json and add group IDs to the 'groups' object."
echo ""
warn "After updating Claude Code, re-run: ~/.claude-bots/patch-server.sh"
