#!/usr/bin/env bash
set -euo pipefail

[[ $# -eq 1 ]] || { echo "usage: customer-pm-route-fixture.sh CUSTOMER_RELEASE" >&2; exit 2; }
release="$(realpath -e "$1")"
server_js="$release/dist/mvp-server.js"
manifest="$release/dist/env-manifest.json"
[[ -f "$server_js" && -f "$manifest" ]] || { echo "CUSTOMER_PM_ROUTE_RELEASE_INCOMPLETE=1" >&2; exit 2; }

fixture_root="$(mktemp -d)"
server_pid=""
cleanup() {
  if [[ -n "$server_pid" ]]; then
    kill "$server_pid" 2>/dev/null || true
    wait "$server_pid" 2>/dev/null || true
  fi
  rm -rf -- "$fixture_root"
}
trap cleanup EXIT

port=$((24000 + RANDOM % 12000))
customer_env="$fixture_root/customer.env"
jq -r '.required[] | .name as $n | if $n=="MVP_GBRAIN_MODE" then "\($n)=disabled" elif $n=="MVP_PUBLIC_MODE" or $n=="MVP_DEV_MODE" or $n=="MVP_SKIP_SERVE" then "\($n)=0" elif .type=="integer" then "\($n)=8091" elif .type=="url" then "\($n)=https://customer.invalid" elif .type=="absolute_path" then "\($n)='"$fixture_root"'/paths/\($n)" else "\($n)=fixture" end' "$manifest" > "$customer_env"
{
  echo "MVP_PORT=$port"
  echo "MVP_BASE_URL=http://127.0.0.1:$port"
  echo "MVP_ATTACH_ORIGIN=http://localhost:$port"
  echo "MVP_DIR=$release/dist"
  echo "MVP_DATA_DIR=$fixture_root/data"
  echo "MVP_INTERNAL_WRITE_SECRET=route-fixture-secret"
} >> "$customer_env"

mkdir -p "$fixture_root/data"
MVP_DATA_DIR="$fixture_root/data" bun -e '
  import { Database } from "bun:sqlite";
  import { join } from "node:path";
  const db = new Database(join(process.env.MVP_DATA_DIR!, "users.db"));
  db.exec(`CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT, email TEXT UNIQUE NOT NULL, name TEXT, google_sub TEXT, tg_user_id TEXT, assistant_bot TEXT, role TEXT NOT NULL DEFAULT "member", created_at TEXT, identity TEXT); CREATE TABLE kv (k TEXT PRIMARY KEY, v TEXT);`);
  db.query("INSERT INTO users (id,email,name,role,created_at) VALUES (1,?,?,?,?)").run("fixture-admin@example.invalid", "fixture-admin", "admin", new Date().toISOString());
  db.query("INSERT INTO kv (k,v) VALUES (?,?)").run("session_secret", "customer-pm-route-fixture-secret");
  db.close();
'
cookie="$(bun -e 'import { createHmac } from "node:crypto"; const v="1"; console.log(`${v}.${createHmac("sha256", "customer-pm-route-fixture-secret").update(v).digest("hex").slice(0,32)}`)')"

set -a
# Values are generated by jq from manifest-owned names and fixture-only literals.
# shellcheck disable=SC1090
source "$customer_env"
set +a
CHANNELLAB_DEPLOYMENT=customer CHANNELLAB_ENV_MANIFEST="$manifest" \
  bun "$server_js" >"$fixture_root/server.log" 2>&1 &
server_pid=$!

ready=0
for _ in $(seq 1 80); do
  if curl -fsS "http://127.0.0.1:$port/" >/dev/null 2>&1; then ready=1; break; fi
  if ! kill -0 "$server_pid" 2>/dev/null; then break; fi
  sleep 0.1
done
if [[ $ready -ne 1 ]]; then
  echo "CUSTOMER_PM_ROUTE_SERVER_START_FAILED=1" >&2
  sed -n '1,120p' "$fixture_root/server.log" >&2
  exit 1
fi

internal_body="$fixture_root/internal.body"
finance_body="$fixture_root/finance.body"
internal_status="$(curl -sS -o "$internal_body" -w '%{http_code}' \
  -H 'x-mvp-internal-secret: route-fixture-secret' \
  "http://127.0.0.1:$port/internal/pm-finance-summary")"
finance_status="$(curl -sS -o "$finance_body" -w '%{http_code}' \
  -H "cookie: mvp_session=$cookie" \
  "http://127.0.0.1:$port/pm/finance")"

echo "CUSTOMER_PM_INTERNAL_STATUS=$internal_status"
echo "CUSTOMER_PM_INTERNAL_BODY=$(tr '\n' ' ' < "$internal_body")"
echo "CUSTOMER_PM_FINANCE_STATUS=$finance_status"
echo "CUSTOMER_PM_FINANCE_BODY=$(tr '\n' ' ' < "$finance_body")"

expected='customer build does not provide PM finance'
if [[ "$internal_status" != "500" || "$finance_status" != "500" ]] ||
   ! grep -Fq "$expected" "$internal_body" ||
   ! grep -Fq "$expected" "$finance_body" ||
   grep -Fq 'loadSecretGcp is not defined' "$internal_body" ||
   grep -Fq 'loadSecretGcp is not defined' "$finance_body"; then
  echo "CUSTOMER_PM_ROUTE_EXPECTATION=FAIL" >&2
  exit 1
fi
echo "CUSTOMER_PM_ROUTE_EXPECTATION=PASS"
